base_url = "https://johnnacion.dev"
title = "johns portfolio"
theme = "apollo"
compile_sass = true
build_search_index = true
minify_html = true
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true

[extra]
toc = true
use_cdn = false
theme = "toggle"
fancy_code = true

menu = [
    { name = "/projects", url = "/projects", weight = 1 },
    { name = "/about", url = "/about", weight = 2 },
]

socials = [
    { name = "linkedin", url = "https://www.linkedin.com/in/john-carter-114a57357/", icon = "linkedin" },
    { name = "github", url = "https://github.com/nuttycream", icon = "github" },
]
