base_url = "https://johnnacion.dev"
theme = "apollo"
taxonomies = [{ name = "tags" }]
minify_html = true
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[extra]
toc = true
use_cdn = false
theme = "toggle"
fancy_code = true

menu = [
    { name = "/projects", url = "/projects", weight = 1 },
    { name = "/about", url = "/about", weight = 2 },
]

socials = [
    { name = "linkedin", url = "https://twitter.com/not_matthias", icon = "linkedin" },
    { name = "github", url = "https://github.com/nuttycream", icon = "github" },
]
