on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/main.yml
      - styles/**
      - templates/**
      - content/**
      - static/**
      - config.toml

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v5

      - name: Cache sussg 
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/sussg
          key: sussg-${{ runner.os }}

      - name: Install sussg
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/nuttycream/sussg 

      - name: Build site
        run: sussg build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=johnnacion
